components/yaml-editor.tsx
yaml-editor.jsx

- removed validate button.
- removed option for toggle theme shortcut

task(remove-btn): removed validate button from yaml editor(IP-3582)

---

components/yaml-editor.tsx

https://yco.atlassian.net/browse/IP-3588
issue no 3 & 11
3: Before:
After:
17: Before:
After:

fix(icon-align): fixed icons alignment

---

components/yaml-editor.tsx

- File selection requirement
- Fixed selection highlight on tree

Bug fix/ip 3587 selection highlight issue

---

components/yaml-editor.tsx

Bug fix/ip 3601 tree render issue

---

components/yaml-editor.tsx

- Updates to delete alert popup dialod
- delete button text color/ continue button
- add cancel metadata auto generation in the second popup

fix(delete): fix title

---

components/yaml-editor.tsx

- Fixed Delete Tree render issue
- Fixed schema and semantic files not focused
- File name validation partial fix
- Specific file not deleted fix
- Shorten metadata

fixed many bugs on editor end

---

components/yaml-editor.tsx

Ticket Link: https://yco.atlassian.net/browse/IP-3622
Changes:
1. Added collapse code.

fix(added-collapse): added collapse on single click(IP-3622)

---

components/yaml-editor.tsx

- Removed full screen when file is not selected

fix full screen issue

---

components/ui/metadata-options.tsx
components/yaml-editor.tsx

- updates to text size
- height of title
- color of title

Bugfix/ip 3588 metadata editor UI fixes

---

components/yaml-editor.tsx

fix(dialog-titles): changed dialog titles (WARNING: merge along with pull 2321 from frontend)

---

components/yaml-editor.tsx

fix(padding): add right padding

---

components/yaml-editor.tsx

fix(metadata-editor): incorporate formatinng

---

components/yaml-editor.tsx

1. Fixed expansion issue of sidebar on first render of editor

fix(Focus-Issue): fixed sidebar expansion on first render

---

components/yaml-editor.tsx

- Fixed red dot disappearance delay issue in metadata editor

Bug fix/ip 3592 red dot persistance

---

components/yaml-editor.tsx

1. Removed toggle theme button

fix(Theme-Removal): removed light and dark mode button

---

components/yaml-editor.tsx

1. Removed content on save if list does not contain name of file

fixed save issue in metadata editor

---

components/ui/metadata-options.tsx
components/yaml-editor.tsx

1. Added classname to pass to yaml-editor

fix(Merge-Dev): added classname for editor

---

components/ui/dialog.tsx
components/yaml-editor.tsx

fix(width): added max width to content

---

components/yaml-editor.tsx

fix(corrupt-file): fixed corrupt file issue

---

components/yaml-editor.tsx

- Fixed mentioned issue.
- The text was already in center.

fix(metadata-editor): fixed issue of metdata editor(DZ-1177)

---

components/yaml-editor.tsx

- fixed gap issues between text and buttons
- fixed pop up title rrequirements

fix(Dialog-box): fixed stated UI issues (DZ-1172)

---

components/yaml-editor.tsx

- Fixed random closing of metadata on saving.

fix(saving-issue): fixed random closing of metadata editor(DZ-1165)
